### ISSUE TITLE
My badge appears as failed build even with successful builds.

### ISSUE THREAD

**Issue by agustif** [pussinboots/heroku-badge#15]
I'm not sure what's going on, my app is deployed successfully but the badge always says failed, it worked with successful builds at some time

**Comment by ChecksumDev** [comment]
Same here, using other heroku badge products like https://github.com/DenisOH/pyheroku-badge and it still bugs, seems to work with other heroku projects though that aren't mine, could be an api bug?

**Comment by george-haddad** [comment]
how does the URL look like?

**Comment by agustif** [comment]
No longer using this will reopen if If I have the problem

**Comment by dhalenok** [comment]
> Same here, using other heroku badge products like https://github.com/DenisOH/pyheroku-badge and it still bugs, seems to work with other heroku projects though that aren't mine, could be an api bug?

I would be really grateful if you could open up an issue.
