### ISSUE TITLE
Flat design

### ISSUE THREAD

**Issue by vbauer** [pussinboots/heroku-badge#3]
Could you please add query parameter to generate flat badges?

**Comment by pussinboots** [comment]
Hi what you mean with flat badges can you provide the images ? Than i can add a query parameter.

**Comment by vbauer** [comment]
I'm mean badges without shades/volume. You can see an example on the shield.io at the bottom of the home page, section "Styles": http://shields.io

**Comment by xvik** [comment]
:+1:

**Comment by pussinboots** [comment]
It's done. The new query parameter is called style and if it is set to flat then it delive a flat png image.

Use it like this https://heroku-badge.herokuapp.com/?app=heroku-badge&style=flat

**Comment by vbauer** [comment]
Thank you very much!
