### ISSUE TITLE
Add type of app to badge

### ISSUE THREAD

**Issue by nahody** [pussinboots/heroku-badge#4]
May a good idea for private repos inside companies, is to add the type (production, development, staging, feature) to the bagde. That way product owners can see their status more detailed.

**Comment by pussinboots** [comment]
Hi sounds like a good idea. 

could be achieved i guess by simple setup so much badge links you need for example.

Development: <a href="https://heroku-badge.herokuapp.com/projects.html"><img alt="Heroku" src="https://heroku-badge.herokuapp.com/?app=heroku-badge-development" style="max-width:100%;"></a>

Production: <a href="https://heroku-badge.herokuapp.com/projects.html"><img alt="Heroku" src="https://heroku-badge.herokuapp.com/?app=heroku-badge-production" style="max-width:100%;"></a>

Did i got your point?

**Comment by nahody** [comment]
Yes, actually I'm doing it manually. Having nice images, would be great. Options could be from git flow: Production (master), Development (develop), Feature, Fix, Hotfix and Stage is important.

**Comment by pussinboots** [comment]
Ok i got it.

**Comment by nahody** [comment]
That way I can use it as component and put it on other services like confluence without losing the "subject" of viewed status.

**Comment by pussinboots** [comment]
I suggest that you describe the scenario a liitle bit more in detail. The heroku badge project is at the moment very simple. Because if i understand you right you want to have one badge that display the status for all repos like that one it does for testcases. http://unitcover.herokuapp.com/api/pussinboots/unitcover/testsuites/badge

**Comment by pussinboots** [comment]
Could be look like 
<svg xmlns="http://www.w3.org/2000/svg" width="400" height="200">
  <defs>
    <linearGradient id="lgr1" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#fff" stop-opacity=".7"/>
      <stop offset=".1" stop-color="#aaa" stop-opacity=".1"/>
      <stop offset=".9" stop-opacity=".3"/>
      <stop offset="1" stop-opacity=".5"/>
    </linearGradient>
  </defs>
  <rect rx="4" y="0" x="0" width="160" height="18" fill="#555"/>
  <rect rx="4" y="0" x="160" width="70" height="18" fill="green"/>
  <rect rx="4" y="0" width="230" height="18" fill="url(#lgr1)"/>
  <rect rx="4" y="17" x="0" width="160" height="18" fill="#555"/>
  <rect rx="4" y="17" x="160" width="70" height="18" fill="green"/>
  <rect rx="4" y="17" width="230" height="18" fill="url(#lgr1)"/>
  <rect rx="4" y="34" x="0" width="160" height="18" fill="#555"/>
  <rect rx="4" y="34" x="160" width="70" height="18" fill="green"/>
  <rect rx="4" y="34" width="230" height="18" fill="url(#lgr1)"/>
  <rect rx="4" y="51" x="0" width="160" height="18" fill="#555"/>
  <rect rx="4" y="51" x="160" width="70" height="18" fill="red"/>
  <rect rx="4" y="51" width="230" height="18" fill="url(#lgr1)"/>
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  <text x="47.5" y="12" fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">Development</text>
  <text x="168.5" y="12" fill="#fff" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">deployed</text>
  <text x="31.5" y="29" fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">Feature</text>
  <text x="168.5" y="29" fill="#fff" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">deployed</text>
  <text x="27.5" y="46" fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">Hotfix </text>
  <text x="168.5" y="46" fill="#fff" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">deployed</text>
  <text x="40.5" y="63" fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">Production</text>
  <text x="170.5" y="63" fill="#fff" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">failed</text>
  
  
  
  
  
  
  
  
  
  
  
  
  
  
</svg>

**Comment by pussinboots** [comment]
Close the issue because of inactivity.
