### ISSUE TITLE
Update image to match other badges

### ISSUE THREAD

**Issue by AnotherKamila** [pussinboots/heroku-badge#7]
All the other badges (for build status, dependences & such) have a unified style, different from the "green" version of this, so this looks weird when used along with those. It would be great if you could update the image style to match that.

**Comment by pussinboots** [comment]
Hi,

i notice your request and will work on it in the next days. if you can help me by for example providing the images then i appreciate that.

**Comment by AnotherKamila** [comment]
Hi,

I don't know what the "canonical" source of the images is, but for example ![example image](https://david-dm.org/anotherkamila/songbook-web.svg) is like that. The code generating it is opensource -- [alanshaw/david-www](https://github.com/alanshaw/david-www).

**Comment by borja** [comment]
+1
I would recommend the same green color as travis "successful build badge"

**Comment by ice-blaze** [comment]
Maybe I'm too pernickety but the right part of the badge have inverted round corners : 
![image](https://cloud.githubusercontent.com/assets/3356843/19785994/1677efc0-9c9c-11e6-8fac-d99e61380a91.png)

**Comment by pussinboots** [comment]
Thanks for the contribution.
